[plugin]          
internal_name = "ToshiBox"          
display_name = "ToshiBox"          
author = "Toshi"          
description = "My own playground for plugin dev"          
punchline = "Hello there"          
repo_url = "https://github.com/Tykku/ToshiBox"          
tags = ["ToshiBox"]          
icon_url = "https://tykku.github.io/ToshiBox/release/images/icon.png"          
assembly_version = "7.2.5.7"          
dalamud_api_level = 12          
download_link_install = "https://tykku.github.io/ToshiBox/release/ToshiBox.zip"          
changelog = "Auto-published version 7.2.5.7"          
